name: PPT
on:
  workflow_dispatch:
    inputs:
      markdown:
        description: 'markdown raw url'
        required: true
        
jobs:
  PPT-Pages:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
  
      - name: Download
        run: curl -o index.md ${{github.event.inputs.markdown}}

      - name: Install Deps
        run: npm i -g markppt
       
      - name: Create PPT
        run: markppt ./index.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
